"""Executive Summary Generator - Aggregates AI syntheses into professional reports."""

import sqlite3
from datetime import datetime
from typing import Tuple


def generate_executive_summary(db) -> Tuple[str, bool]:
    """Generate full executive summary from all themes and syntheses."""
    
    conn = sqlite3.connect(db.db_path)
    cursor = conn.cursor()
    
    project_title = "AIMS Systematic Review"
    date_generated = datetime.now().strftime("%Y-%m-%d")
    
    cursor.execute("SELECT value FROM settings WHERE key = 'project_title'")
    title_result = cursor.fetchone()
    if title_result:
        project_title = title_result[0]
    
    rq_codes = ["RQ1", "RQ2", "RQ3", "RQ4", "RQ5"]
    
    report_lines = [
        f"# {project_title}",
        f"## Executive Summary Report",
        f"*Generated by AIMS on {date_generated}*",
        "",
        "---",
        "",
        "## 📋 Methodology Summary",
        "",
        "This systematic review was conducted using the **Automated Intelligence Mapping System (AIMS)**,",
        "a Streamlit-based research pipeline for systematic literature review automation.",
        "",
        "### Pipeline Stages:",
        "",
        "1. **Import & Deduplication**: CSV/BibTeX/RIS files imported, duplicates detected via DOI matching.",
        "2. **Screening**: Title/Abstract screening with dual-reviewer consensus.",
        "3. **Quality Assessment**: 5-point quality scoring using modified CASP criteria.",
        "4. **Evidence Extraction**: Fragment extraction linked to research questions.",
        "5. **Thematic Synthesis**: Open coding → Theme organization → Traceability matrix.",
        "",
        "---",
        "",
        "## 🔍 Key Findings by Research Question",
        "",
    ]
    
    has_themes = False
    wl_gl_divergence = []
    
    for rq in rq_codes:
        cursor.execute("""
            SELECT id, theme_label, ai_synthesis, wl_synthesis, gl_synthesis
            FROM themes 
            WHERE rq_code = ?
            ORDER BY created_at DESC
        """, (rq,))
        themes = cursor.fetchall()
        
        if themes:
            has_themes = True
            report_lines.append(f"### {rq}")
            report_lines.append("")
            
            for theme in themes:
                theme_id, theme_label, ai_synth, wl_synth, gl_synth = theme
                
                report_lines.append(f"**Theme: {theme_label}**")
                report_lines.append("")
                
                if ai_synth:
                    report_lines.append("*AI Synthesis:*")
                    report_lines.append(ai_synth)
                    report_lines.append("")
                
                if wl_synth and gl_synth:
                    wl_gl_divergence.append({
                        "theme": theme_label,
                        "rq": rq,
                        "wl": wl_synth,
                        "gl": gl_synth
                    })
            
            report_lines.append("")
    
    if not has_themes:
        report_lines.append("*No themes synthesized yet.*")
        report_lines.append("")
    
    report_lines.append("---")
    report_lines.append("")
    report_lines.append("## 📊 WL vs GL Divergence Analysis")
    report_lines.append("")
    
    if wl_gl_divergence:
        report_lines.append("This section highlights conceptual divergence between White Literature (WL) and Gray Literature (GL).")
        report_lines.append("")
        
        for divergence in wl_gl_divergence:
            report_lines.append(f"### {divergence['theme']} ({divergence['rq']})")
            report_lines.append("")
            report_lines.append("**White Literature Perspective:**")
            report_lines.append(divergence['wl'])
            report_lines.append("")
            report_lines.append("**Gray Literature Perspective:**")
            report_lines.append(divergence['gl'])
            report_lines.append("")
    else:
        report_lines.append("*No WL/GL comparative syntheses generated.*")
        report_lines.append("")
    
    report_lines.append("---")
    report_lines.append("")
    report_lines.append("## 📚 References")
    report_lines.append("")
    
    cursor.execute("""
        SELECT title, authors, year, doi, literature_type
        FROM articles
        WHERE screening_status IN ('included', 'final_included')
        ORDER BY year DESC
    """)
    articles = cursor.fetchall()
    
    if articles:
        report_lines.append("### Included Studies")
        report_lines.append("")
        
        for art in articles:
            title, authors, year, doi, lit_type = art
            citation = f"- {authors} ({year}). *{title}*"
            if doi:
                citation += f". DOI: {doi}"
            citation += f" [{lit_type}]"
            report_lines.append(citation)
        
        report_lines.append("")
    else:
        report_lines.append("*No articles included yet.*")
        report_lines.append("")
    
    conn.close()
    
    full_report = "\n".join(report_lines)
    has_content = has_themes or len(wl_gl_divergence) > 0
    
    return full_report, has_content


def aggregate_theme_summaries(themes: list) -> str:
    """Aggregate multiple theme summaries into cohesive text."""
    if not themes:
        return ""
    
    aggregated = []
    for theme in themes:
        if theme[2]:
            aggregated.append(f"- **{theme[1]}**: {theme[2]}")
    
    return "\n".join(aggregated) if aggregated else "No synthesis available."